title: аккредитованный турагент ведущих судовладельцев России
description: аккредитованный турагент ведущих судовладельцев России с 2001 года
url: https://www.cruise-volna.ru
company: Круиз-Волна
author: Круиз-Волна
keywords: речные круизы, туры по России, отдых на теплоходе
email: support@superuser.su
baseurl: /
include:
  - _pages
exclude: [LICENSE.txt, README.md]
link: "https://www.cruise-volna.ru"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap