title: аккредитованный турагент ведущих судовладельцев России
company: Круиз-Волна
author: Круиз-Волна
keywords: речные круизы, туры по России, отдых на теплоходе
email: webmaster@rechnoyvokzal.ru
url: https://www.cruise-volna.ru
description: >
  аккредитованный турагент ведущих судовладельцев России с 2001 года
baseurl: "/"
include:
  - _pages
exclude: [LICENSE.txt, README.md]
link: "https://www.cruise-volna.ru"
markdown: kramdown
plugins:
  - jekyll-feed